baseURL = "https://finsberg.github.io/simula_code_web/"
languageCode = "en-us"
title = "Code@Simula"
description="Code and software tools written by researchers at Simula Research Laboratory"
# theme = "hyde-y"
theme = "kraiklyn"

# metaDataFormat = "yaml"






publishDir = "docs"



[params]
copyright="2018 Simula Research Laboratory"
externalTitle="External resources"
sidebarColor="simula-orange"

[[menu.shortcuts]]
name = "Simula website"
url = "https://www.simula.no"
weight = 10

[[menu.shortcuts]]
name = "Computational Physiology at Simula"
url = "https://www.simula.no/research/projects/department-computational-physiology"
weight = 20